In [1]:
import numpy as np

In [4]:
arr1 = np.array([1,2,3])
print(arr1)
# Static (Immutable for size) and Homogeneous (one data type)

[1 2 3]


In [5]:
# Python list
[1,2,3] + [4,5,6]

[1, 2, 3, 4, 5, 6]

In [7]:
# Numpy- Element wise arithmetic
np.array([1,2,3]) + np.array([4,5,6])

array([5, 7, 9])

In [8]:
# Logical operators in Numpy
np.logical_and(np.array([True, False]), np.array([True, True]))

array([ True, False])

In [16]:
# Multidimensional
arr1 = np.array([[1,2], [3,4], [10,20], [30,40]])
print(arr1.shape)
print(arr1.size)
print(arr1.ravel())

(4, 2)
8
[ 1  2  3  4 10 20 30 40]


In [22]:
# Python list
l1 = [1,2,3,4,5,6]
l2 = [[1,2], [10,20]]
print(l1[1])
print(l1[1:4])
print(l1[4:])
print(l2[0][1])

2
[2, 3, 4]
[5, 6]
2


In [24]:
#Numpy
arr1 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr1)
print(arr1[0, 0, 1])
print(arr1[0, 0, ...])

arr2 = np.array([10, 20, 30, 40, 50])
print(arr2[[0, 2, 4]])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
2
[1 2 3]
[10 30 50]


In [39]:
# From a numpy array of words, extract elements that start with an 'a'

# Using loop
words = np.array(['asd', 'qwe', 'zxc', 'asf', 'qwr', 'zxv'])
result = []
for item in words:
    if item.startswith('a'):
        result.append(item)
print(result)

# Using comprehension
words = np.array(['asd', 'qwe', 'zxc', 'asf', 'qwr', 'zxv'])
result = [item for item in words if item.startswith('a')]
print(result)

['asd', 'asf']
['asd', 'asf']


In [41]:
# Indexing with conditions
arr1 = np.array([1, 2, 3, 4, 5, 6])
print(arr1 % 3 == 0)
arr1[arr1 % 3 == 0]

[False False  True False False  True]


array([3, 6])

In [44]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print(np.vstack((arr1, arr2)))

arr3 = np.array([[1, 2], [3, 4]])
print(np.vsplit(arr3, 2))

[[1 2 3]
 [4 5 6]]
[array([[1, 2]]), array([[3, 4]])]


In [68]:
# Get the top right 2 x 2 slice from an 8 x 8 ndarray matrix.

# Created with comprehension
mat = np.array([[i for i in range(x, x+8)] for x in range(1,65,8)])
print(mat)
print(mat[0:2,6:8])

print()

# Without comprehension
mat = np.array(np.vstack([range(1,9), range(9,17), range(17,25), range(25,33),
                         range(33,41), range(41,49), range(49,57), range(57,65)]))
print(mat)
print(mat[0:2,6:8])

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]
 [25 26 27 28 29 30 31 32]
 [33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48]
 [49 50 51 52 53 54 55 56]
 [57 58 59 60 61 62 63 64]]
[[ 7  8]
 [15 16]]

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]
 [25 26 27 28 29 30 31 32]
 [33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48]
 [49 50 51 52 53 54 55 56]
 [57 58 59 60 61 62 63 64]]
[[ 7  8]
 [15 16]]
